"""empty message

Revision ID: 573aaebaabf3
Revises: 
Create Date: 2020-02-04 20:52:15.084969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573aaebaabf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('mail', sa.String(length=128), nullable=True),
    sa.Column('pwd', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
