"""empty message

Revision ID: 94331b7b75d8
Revises: 29dc3e7d2784
Create Date: 2020-01-21 21:54:06.267575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94331b7b75d8'
down_revision = '29dc3e7d2784'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('content', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post')
    # ### end Alembic commands ###
